version: "3.9"

services:
  user-service:
    build: ./user-service
    container_name: user-service
    environment:
      SECRET_KEY: dev-secret-123
      DB_PATH: /app/users.db
    volumes:
      - ./user-service/users.db:/app/users.db

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      DB_PATH: /app/products.db
    volumes:
      - ./product-service/products.db:/app/products.db

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      DB_PATH: /app/orders.db
    volumes:
      - ./order-service/orders.db:/app/orders.db

  payment-service:
    build: ./payment-service
    container_name: payment-service
    environment:
      DB_PATH: /app/payments.db
    volumes:
      - ./payment-service/payments.db:/app/payments.db

  notification-service:
    build: ./notification-service
    container_name: notification-service
    environment:
      DB_PATH: /app/notifications.db
    volumes:
      - ./notification-service/notifications.db:/app/notifications.db

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      DB_PATH: /app/inventory.db
    volumes:
      - ./inventory-service/inventory.db:/app/inventory.db

  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
      - notification-service
      - inventory-service
